FROM openjdk:8-jre-alpine
ADD target/ecosystem-recommendation-0.0.1-SNAPSHOT.jar ecosystem-recommendation-0.0.1-SNAPSHOT.jar
EXPOSE 9000
CMD ["java", "-jar", "ecosystem-recommendation-0.0.1-SNAPSHOT.jar"]