server:
  port: 9090

management:
  security:
    enabled: false

auth-server: http://localhost:9090/auth/

zuul:
  routes:
    auth:
      path: /auth/**
      url: http://localhost:9000/auth/
      sensitive-headers:
    resource:
      path: /resource/**
      url: http://localhost:8091/
#      sensitive-headers:  
    static:
      path: /static/**

spring:
  application:
    name: web-app
  thymeleaf:
    cache: false

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9090/auth/oauth/token
      userAuthorizationUri: http://localhost:9090/auth/oauth/authorize
      clientId: web-app
      clientSecret: secret
      preEstablishedRedirectUri: http://localhost:9090/login
      registeredRedirectUri: http://localhost:9090/login
      useCurrentUri: false

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----

#logging:
#  level:
#    org.springframework.security: DEBUG
    